// Generated by: npx supabase gen types typescript --project-id <your-project-ref>
// Run that command to regenerate after schema changes.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]
export interface Database { public: { Tables: Record<string, unknown>; Views: Record<string, unknown>; Functions: Record<string, unknown> } }
